# Generated by Django 4.2.9 on 2024-01-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination_email",
                    models.EmailField(
                        max_length=254, verbose_name="Destination Email"
                    ),
                ),
                (
                    "email_purpose",
                    models.CharField(
                        choices=[
                            ("C", "Task Created"),
                            ("F", "Task Finished"),
                        ],
                        max_length=1,
                        verbose_name="Email Purpose",
                    ),
                ),
                (
                    "delivered",
                    models.BooleanField(
                        default=False, verbose_name="Delivered"
                    ),
                ),
                (
                    "error_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Info"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project_manager.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
